name: Evaluation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run action
      uses: jainal09/strivio@master 
      with:
        oath: ${{ secrets.oath }}
